[package]
name    = "atlas-core"
version = "0.1.0"
edition = "2021"

[dependencies]
atlas-ir         = { path = "../ir" }
atlas-connectors = { path = "../connectors" }
atlas-git        = { path = "../git" }
atlas-parser     = { path = "../parser" }
atlas-storage    = { path = "../storage" }
anyhow           = { workspace = true }
indexmap         = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
sha2             = { workspace = true }
tracing          = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
chrono   = { workspace = true }
